server:
  version: @project.version@
  port: 8000
  servlet:
    context-path: /dict-service

spring:
  application:
    name: dict-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  messages:
    basename: messages_en_US
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.22.140:3306/dict_service?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

# 日志文件配置
logging:
  config: classpath:logback-spring.xml
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.leadtrans.dictservice.common.repository.entity
  global-config:
    db-config:
      insert-strategy: ignored  # "忽略判断", 所有字段都插入
      update-strategy: ignored  # "忽略判断", 所有字段都更新
http:
  pool:
    maxTotal: 500
    defaultMaxPerRoute: 300
    connectTimeout: 180000
    connectionRequestTimeout: 180000
    socketTimeout: 180000
    validateAfterInactivity: 30000

swagger:
  enable: false

management:
  # 自定义端点路径
  # base-path: '/dict-service'
    # *启用所有Actuator端点，仅暴露部分端点：health,info,metrics
  endpoints:
    web:
      exposure:
        include: '*'